### ISSUE TITLE
staticpaths are deprecated. Use Make instead.

### ISSUE THREAD

**Issue by biro-mark** [staticjinja/staticjinja#96] opened 2020-11-06 19:41 UTC
The docs say to use the --static flag to serve static files https://staticjinja.readthedocs.io/en/latest/user/quickstart.html?highlight=static#configuration. 

Here's what I tried
`staticjinja watch --static static`

I get this warning
 `env/lib/python3.6/site-packages/staticjinja/staticjinja.py:97: UserWarning: staticpaths are deprecated. Use Make instead.
  warnings.warn("staticpaths are deprecated. Use Make instead.")`

And my static files under `templates/static` were not copied

**Comment by NickCrews** [comment] 2020-11-10 02:23
Closing as duplicate of https://github.com/staticjinja/staticjinja/issues/97

**Closed by NickCrews** 2020-11-10 02:23 UTC
